<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CyclingPeak.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CyclingPeak.Application\CyclingPeak.Application.csproj" />
    <ProjectReference Include="..\CyclingPeak.Domain\CyclingPeak.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="BCrypt.Net-Next" />
    <PackageReference Include="MailKit" />
  </ItemGroup>
</Project>
